Add production environment
benjaminbrassart/transcendence pull request #415
Opened 2023-04-24 04:08 UTC by benjaminbrassart

TODO:
- Fix frontend build environment variables (Docker does NOT pass env variables to build stage)

Use Dockerfiles instead of writing the commands inside docker-compose.yml
Move `.env` to `.env.development`
Add `.env.production`
Add script `setenv.sh` to switch between environments
Add docker-compose.dev.yml (dev)
Add docker-compose.override.yml (prod)
Change Makefile so it uses the development docker-compose configuration

2023-04-27 12:31 UTC, benjaminbrassart commented
https://stackoverflow.com/a/52430444

2023-05-04 21:17 UTC, Balgor18 requested changes
i just add 2 comment about remove 1 things for sure and the other i think we dont need it

2023-05-04 21:17 UTC, Balgor18 commented on backend/src/main.ts
Question about the line 24. Do we really need a adapter for the socket ?

2023-05-04 21:17 UTC, Balgor18 commented on docker-compose.yml
> +      NEST_DEBUG: true # TODO REMOVE THIS ('true' break compilation on other machines)
We dont need it anymore. We can erase

2023-05-04 21:27 UTC, BarbaraC12 approved these changes

2023-05-04 21:27 UTC, BarbaraC12 commented on frontend/.env
> +../.env
is this very necessary ?

2023-05-04 22:05 UTC, jesuisstan commented
Cannot login neigher with 42 nor with Github. Guess, something is wrong with CALLBACK_URL

in address line see this: "http://localhost:3080/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch"

2023-05-06 14:08 UTC, benjaminbrassart commented on docker-compose.yml
> +      NEST_DEBUG: true # TODO REMOVE THIS ('true' break compilation on other machines)
Done

2023-05-06 14:10 UTC, benjaminbrassart commented on frontend/.env
> +../.env
The file is a symbolic link, its content is the link's target. I suppose, however, that we could get rid of it

2023-05-06 14:14 UTC, benjaminbrassart commented
> Cannot login neigher with 42 nor with Github. Guess, something is wrong with CALLBACK_URL
> 
> in address line see this: "http://localhost:3080/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch"

Backend url becomes `{frontendUrl}/api` in production, the backend is hidden behind a reverse proxy. This is because CORS errors are raised when using http on another host than localhost. So, the redirect url for github oauth flow would be `http://10.2.1.5:3000/api/auth/github/redirect`

2023-05-06 14:37 UTC, Balgor18 approved these changes

2023-05-06 14:57 UTC, benjaminbrassart commented on frontend/.env
> +../.env
Done

2023-05-06 14:58 UTC, benjaminbrassart commented on backend/src/main.ts
I honestly don't know, I merged with what had been done previously.

2023-05-06 17:14 UTC, Balgor18 approved these changes

2023-05-06 17:15 UTC, BarbaraC12 approved these changes

2023-05-06 17:16 UTC, BarbaraC12 approved these changes

2023-05-06 17:17 UTC, Balgor18 approved these changes

2023-05-06 20:35 UTC, Balgor18 approved these changes

2023-05-07 02:06 UTC, jesuisstan reviewed
ok

2023-05-07 02:06 UTC, jesuisstan approved these changes

2023-05-07 05:17 UTC, merged